name: Deploy WordPress Theme (Live)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clear old theme files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 92.249.46.134
          username: u692901164
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          script: |
            rm -rf /public_html/wp-content/themes/deepak-sherawat-web-developer/*

      - name: Deploy via SSH (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 92.249.46.134
          username: u692901164
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          source: "./wp-content/themes/deepak-sherawat-web-developer"
          target: "/public_html/wp-content/themes/"
