name: Deploy WordPress Theme (Live)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Theme to Live Site
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 92.249.46.134
          username: u692901164
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          port: 65002

          # 👇 IMPORTANT: sirf theme folder upload karo
          source: "wp-content/themes/deepak-sherawat-web-developer/*"

          # 👇 LIVE SITE theme folder
          target: "/home/u692901164/public_html/wp-content/themes/deepak-sherawat-web-developer/"

          overwrite: true
